name: RewardSystem
version: 1.1.3
main: provanasservices.rewardsystem.Main
api-version: 1.16
log_prefix: REWARDSYSTEM
commands:
  rewardsystem:
    description: Main command
    usage: /<command>
    permission: op
softdepend:
  - PlaceholderAPI